expo/entity

.github/workflows/tests.yml, .gitignore, packages/entity-cache-adapter-redis/package.json, packages/entity-database-adapter-knex/package.json, packages/entity-example/package.json, packages/entity/package.json, resources/jest-integration.config.js, resources/jest.config.js
Closes #10.
Use action, upload all clover code coverage reports. Next will be figuring out integration tests.
Wait for CI run.
=> Add codecov to test action

.github/workflows/tests.yml
Closes #14 
Trying out docker-compose setup for integration tests.
Before commit, add integration test upload codecov upload step.
Wait for CI.
=> Run integration tests in github action

packages/entity/src/entityUtils.ts
=> Document entityUtils

packages/entity/src/Entity.ts, packages/entity/src/__tests__/Entity-test.ts
https://github.com/expo/entity/pull/30#pullrequestreview-423003224
`yarn tsc`
=> Fix async method naming in Entity

packages/entity-example/package.json, yarn.lock
https://github.com/advisories/GHSA-w42g-7vfc-xf37
Upgrade `apollo-server-koa`.
`yarn test`
=> fix: upgrade Apollo server for security advisory

CHANGELOG.md, lerna.json, packages/entity-cache-adapter-redis/CHANGELOG.md, packages/entity-cache-adapter-redis/package.json, packages/entity-database-adapter-knex/CHANGELOG.md, packages/entity-database-adapter-knex/package.json, packages/entity-example/CHANGELOG.md, packages/entity-example/package.json, packages/entity/CHANGELOG.md, packages/entity/package.json
See changelog for included changes.
=> Cut v0.5.0

README.md
Rather than using standard lerna "do everything", I've been using a slightly modified version that goes through the normal PR process to run CI.
Update readme.
Will follow these steps exactly when releasing new version shortly.
=> docs: update readme for release process

packages/entity-cache-adapter-local-memory/src/GenericLocalMemoryCacher.ts, packages/entity-cache-adapter-local-memory/src/LocalMemoryCacheAdapter.ts, packages/entity-cache-adapter-local-memory/src/LocalMemoryCacheAdapterProvider.ts, packages/entity-cache-adapter-local-memory/src/__tests__/LocalMemoryCacheAdapter-test.ts, packages/entity-cache-adapter-redis/src/GenericRedisCacher.ts, packages/entity/src/IEntityGenericCacher.ts
implement ide's renaming feedback from https://github.com/expo/universe/pull/9106
=> chore: better variable and method naming

packages/entity/src/index.ts
Forgot to do this in https://github.com/expo/entity/commit/6b6e70e75f7e42a4dce13edeb406a4d88d9264f0
Add to index.
Wait for CI.
=> fix: add composed cache to index

packages/entity/src/ComposedEntityCacheAdapter.ts, packages/entity/src/ComposedSecondaryEntityCache.ts, packages/entity/src/EntityAssociationLoader.ts
Closes ENG-5697.
Add doc, move other docs to fix generation of docs.
N/A
=> docs: add docblock for EntityAssociationLoader and fix other docs

README.md
=> docs: update readme deployment

.github/workflows/docs.yml, README.md
When the master branch was renamed to main, this was forgotten.
Fix.
Inspect.
=> ci: fix github actions docs workflow branch

packages/entity/src/EntityDatabaseAdapter.ts, packages/entity/src/EntityLoader.ts
Closes ENG-6124.
@kgc00 noted that this was a bit confusing, so this PR updates the documentation to be clearer.
Update/add comments.
`yarn tsc`
=> docs: improve documentation for FieldEqualityCondition

packages/entity-database-adapter-knex/src/__integration-tests__/PostgresEntityIntegration-test.ts
Noticed that the test coverage for this feature was pretty low. Easy enough to add additional test coverage.
Add tests for other isolation levels.
Run test.
=> chore: add more test coverage to postgres transaction isolation levels

packages/entity-database-adapter-knex/package.json
Just to test that the upgrade doesn't cause any integration test failures. This way apps that use entity can be assured that this upgrade should be safe.
Upgrade.
Run tests.
=> chore: update pg package to latest version

package.json, yarn.lock
Upgrade typescript. 
Scan the changelog, don't see anything that would affect us: https://devblogs.microsoft.com/typescript/announcing-typescript-5-7/
CI
=> chore: upgrade typescript and related packages

typedoc.json
One more fix of typedoc generation.
Update excludes.
`yarn typedoc`, preview generated html.
=> chore: fix typedoc again

package.json, packages/entity-cache-adapter-local-memory/package.json, packages/entity-cache-adapter-redis/package.json, packages/entity-codemod/package.json, packages/entity-database-adapter-knex/package.json, packages/entity-example/package.json, packages/entity-full-integration-tests/package.json, packages/entity-ip-address-field/package.json, packages/entity-secondary-cache-local-memory/package.json, packages/entity-secondary-cache-redis/package.json, packages/entity-testing-utils/package.json, packages/entity/package.json, yarn.lock
Before releasing the next version, it's good to keep the dependencies of this as up-to-date as possible. This PR updates the dependencies that are easy to update and safe.
Audit package.json files, update where applicable.
CI
=> chore: upgrade dependencies

README.md
A few minor changes to the readme to be more precise about what the three core functions of entity are (definition & ORM, authorization, caching).
Update sentences.
Proofread.
=> chore: update README to be more precise

packages/entity/src/EntityMutationValidator.ts, packages/entity/src/IEntityCacheAdapter.ts, packages/entity/src/IEntityCacheAdapterProvider.ts, packages/entity/src/IEntityDatabaseAdapterProvider.ts, packages/entity/src/IEntityGenericCacher.ts, packages/entity/src/__tests__/GenericEntityCacheAdapter-test.ts, packages/entity/src/__tests__/GenericSecondaryEntityCache-test.ts
Brings test coverage of testable lines to 100%.
Add ignores to interface-only files. Adds a test for untested file.
See codecov report in linked comment.
=> chore: improve test coverage
