- README.md
- packages/entity-cache-adapter-redis/README.md
- packages/entity-database-adapter-knex/README.md
- packages/entity/README.md
For those browsing the github, having links to documentation can be helpful.
Preview readme markdown.
> Add links to doc site in readmes

- .vscode/settings.json
- package.json
- packages/entity-database-adapter-knex/src/PostgresEntityDatabaseAdapter.ts
- yarn.lock
Release notes: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-9.html#breaking-changes
For this project, the changes that affect us are:
- speed improvements
- Type Parameters That Extend any No Longer Act as any
Upgrade in package.json
`yarn test`
`yarn integration`
`yarn typedoc` (depends on typescript)
> Upgrade typescript to 3.9

- packages/entity/src/EntityPrivacyPolicy.ts
- packages/entity/src/index.ts
- packages/entity/src/rules/AlwaysAllowPrivacyPolicyRule.ts
- packages/entity/src/rules/AlwaysDenyPrivacyPolicyRule.ts
- packages/entity/src/rules/AlwaysSkipPrivacyPolicyRule.ts
- packages/entity/src/rules/PrivacyPolicyRule.ts
- packages/entity/src/rules/__tests__/AlwaysAllowPrivacyPolicyRule-test.ts
- packages/entity/src/rules/__tests__/AlwaysDenyPrivacyPolicyRule-test.ts
- packages/entity/src/rules/__tests__/AlwaysSkipPrivacyPolicyRule-test.ts
- packages/entity/src/testfixtures/PrivacyPolicyRuleTestUtils.ts
This adds more documentation to the privacy policy classes included with the library.
Closes #20.
Run tests to ensure file rename is okay.
> Add more documentation to privacy policy classes

- packages/entity/src/EnforcingEntityLoader.ts
- packages/entity/src/EntityLoader.ts
- packages/entity/src/__tests__/EnforcingEntityLoader-test.ts
- packages/entity/src/__tests__/EntityLoader-test.ts
One common use case we're noticing is wanting to check if an ID corresponds to one table or another (only useful for UUID primary key tables).
Another use case is determining whether an ID that should exist truly does (loading permalink page). While this can be handled cleanly with a good error boundary, it still makes sense to have this API available when preferred.
Closes #12.
Add method, enforcing method, and tests. Also add test to ensure consistent API between loader and enforcing loader.
Run tests.
> Add loadByIDNullableAsync loader method

- packages/entity/src/Entity.ts
- packages/entity/src/ReadonlyEntity.ts
- packages/entity/src/__tests__/Entity-test.ts
- packages/entity/src/__tests__/ReadonlyEntity-test.ts
- packages/entity/src/index.ts
Closes #21. 
Add a set of new static methods that we've found would be useful in expo server.
Run new tests.
> Add ability to check update and delete policies outside of mutation

- packages/entity/src/EntityAssociationLoader.ts
- packages/entity/src/__tests__/EntityAssociationLoader-test.ts
https://github.com/expo/entity/issues/45
This adds two basic fan out queries for a two-entity relation (no chain fan-outs yet).
1. Add tests.
1. Add fan out association load methods.
Run tests.
> feat: add two fan out methods to association loader

- .github/workflows/tests.yml
I just wasted ~2 hours on this, so I bet it'll affect others as well.
1. Create branch A at base T, add some commits, create PR(A). See checkout passes and no conflicts.
1. Create branch B at base T, add some commits that create logical conflict with branch A, create PR(B). See checkout passes and no conflicts.
1. Land PR(B) into master.
1. Push additional commit only changing comments to branch A to address comments on PR(A). See that the build is now failing in CI. Run the build locally on branch A and see that it is passing. Waste 2 hours only to find out that instead of running the build on branch A as is represented in PR(A), the "checkout" action doesn't actually "checkout" branch. Instead it creates a merge commit of all the commits on the branch into the current state of the …
> ci: fix checkout action to checkout branch at current state

- packages/entity-database-adapter-knex/src/index.ts
- packages/entity/src/EnforcingEntityLoader.ts
- packages/entity/src/EntityAssociationLoader.ts
- packages/entity/src/EntityCompanion.ts
- packages/entity/src/EntityCompanionProvider.ts
- packages/entity/src/EntityLoader.ts
- packages/entity/src/EntityLoaderFactory.ts
- packages/entity/src/EntityMutator.ts
- packages/entity/src/ViewerContext.ts
- packages/entity/src/ViewerScopedEntityCompanion.ts
- packages/entity/src/ViewerScopedEntityCompanionProvider.ts
- packages/entity/src/ViewerScopedEntityLoaderFactory.ts
- packages/entity/src/ViewerScopedEntityMutatorFactory.ts
- packages/entity/src/__tests__/EnforcingEntityLoader-test.ts
- packages/entity/src/__tests__/EntityMutator-test.ts
- packages/entity/src/__tests__/ViewerScopedEntityCompanion-test.ts
- packages/entity/src/__tests__/ViewerScopedEntityLoaderFactory-test.ts
- packages/entity/src/__tests__/ViewerScopedEntityMutatorFactory-test.ts
- packages/entity/src/utils/testing/PrivacyPolicyRuleTestUtils.ts
- Need to export `PostgresEntityDatabaseAdapterProvider` for usage externally.
- Default generic value for `TSelectedFields` unnecessary in most internal APIs.
- Some logical merge conflicts in `EntityAssociationLoader`
`yarn tsc`
> fix: correct some typing issues and exports

- packages/entity/src/utils/testing/StubCacheAdapter.ts
https://github.com/expo/entity/commit/4e40b2e521407e521d236978ec3b3b56db3990be#diff-7787fea5a7ed6c1892424d39f09dbc4aR51 added a companion-wide stub cache adapter to better simulate testing a real external cache adapter. Unfortunately, the cache key generation function for the stub cache adapter wasn't updated accordingly, so keys for entities from different tables could collide.
Use a more comprehensive cache key generation function.
`yarn tsc`
> fix: fix stub cache key generation for global cache

- packages/entity/src/EntityMutator.ts
4e40b2e521407e521d236978ec3b3b56db3990be incorrectly didn't update the set of fields that could be mutated for an entity that selects a subset of fields.
Update types.
`yarn tsc`
Use typeahead and see that only that entity's field subset are suggested.
> fix: update setField to correct typing

- .github/workflows/docs.yml
- .github/workflows/tests.yml
- package.json
- packages/entity-cache-adapter-redis/package.json
- packages/entity-database-adapter-knex/package.json
- packages/entity-example/package.json
- packages/entity/package.json
- packages/entity/src/EntityMutator.ts
- packages/entity/src/ReadonlyEntity.ts
- packages/entity/src/__tests__/entityUtils-test.ts
- packages/entity/src/entityUtils.ts
- tsconfig.json
- yarn.lock
https://github.com/advisories/GHSA-p6mc-m468-83gw
Figured we don't actually need lodash. 
- `pick` is easy to re-create for our needs (less edge cases due to typescript). 
- Don't actually need `cloneDeep` for mutator, since all we need to ensure is that `setField` doesn't change the original object, and `setField` doesn't support deep changes to objects.
Remove `lodash` dependencies, add new method.
Run tests.
> fix!: remove lodash dependency for vuln, require node 12

- packages/entity-database-adapter-knex/src/__integration-tests__/PostgresEntityIntegration-test.ts
- packages/entity-database-adapter-knex/src/testfixtures/PostgresTriggerTestEntity.ts
- packages/entity/src/EntityCompanion.ts
- packages/entity/src/EntityCompanionProvider.ts
- packages/entity/src/EntityMutationTrigger.ts
- packages/entity/src/EntityMutator.ts
- packages/entity/src/EntityMutatorFactory.ts
- packages/entity/src/EntityQueryContext.ts
- packages/entity/src/__tests__/EntityCompanion-test.ts
- packages/entity/src/__tests__/EntityMutator-test.ts
- packages/entity/src/index.ts
This PR adds mutation triggers, which are similar to [active record callbacks](https://guides.rubyonrails.org/active_record_callbacks.html). They allow entity authors to specify code that runs before and after mutations, and a special callback that occurs after commit of the transaction.
Use cases:
- Audit logging (similar to https://github.com/paper-trail-gem/paper_trail)
- Third-party service calls to keep data in sync
- Email sending
- etc...
Note that for now, this is separate from full entity validation (not yet implemented), but that will be done in a similar way. Depending on the transaction semantics we want for validation it may be exactly the same as `beforeAll` but it's unclear.
Add ability to specify features, add tests.
Run tests.
> feat: mutation triggers

- packages/entity/src/EntityMutator.ts
Before this PR, if a field was `CASCADE_DELETE_INVALIDATE_CACHE` deletion behavior it wouldn't run transitive triggers even though the underlying reference would be deleted by the database foreign key.
This fixes that by doing all recursing through the delete method and just not deleting from the database if a boolean flag is specified. While I'm normally against boolean flags, because this is a private internal method I'm more okay with it.
Concretely the case this fixes is:
Entity A has field `b_id` with behavior CASCADE_DELETE_INVALIDATE_CACHE referencing an Entity B.
Entity B has a trigger that runs during or after deletion (including afterCommit).
Previously B's triggers wouldn't be run. Now they are run.
Run tests. This is very extensively tested so the fact that no test changes …
> fix: ensure transitive deletion triggers are run for CASCADE_DELETE_INVALIDATE_CACHE

- packages/entity-database-adapter-knex/src/__integration-tests__/PostgresEntityIntegration-test.ts
- packages/entity-database-adapter-knex/src/testfixtures/PostgresValidatorTestEntity.ts
- packages/entity/src/EntityCompanion.ts
- packages/entity/src/EntityCompanionProvider.ts
- packages/entity/src/EntityMutationTrigger.ts
- packages/entity/src/EntityMutator.ts
- packages/entity/src/EntityMutatorFactory.ts
- packages/entity/src/__tests__/EntityCompanion-test.ts
- packages/entity/src/__tests__/EntityMutator-test.ts
Implements validation for entity mutations. Validators are specified by the user, and run before every create and update mutation. Validators are run before any triggers.
https://github.com/expo/entity/issues/25
> feat: entity mutation validators

- packages/entity/src/EnforcingEntityLoader.ts
- packages/entity/src/EntityAssociationLoader.ts
- packages/entity/src/EntityCompanion.ts
- packages/entity/src/EntityLoader.ts
- packages/entity/src/EntityLoaderFactory.ts
For entities with field selection, they should only be allowed to use the selected fields for loading. Closes #71.
Update types, `yarn tsc`
`yarn tsc`
> fix: fix incorrect loader types for field selecitons

- packages/entity/src/EntityLoader.ts
- packages/entity/src/__tests__/EnforcingEntityLoader-test.ts
- packages/entity/src/__tests__/cases/TwoEntitySameTableDisjointRows-test.ts
Closes #61.
The issue is that when this was called via a loadMany* method, the first instance of failure would cause the full call to fail. The better behavior is to wrap the constructor in a result-producing try/catch and propagate the result to the caller (except in the enforcing case obviously).
Note that this is a breaking change because it changes the behavior of non-enforcing loadMany* calls.
1. surround constructor call with try/catch
1. return failed results now instead of throwing
Run new test code.
> fix!: constuctor thrown exceptions for loadMany

- package.json
- typedoc.json
- yarn.lock
Broken in 9891e7469467a28589f529c8d87b10fc2232d3ff.
Revert upgrade to these packages.
`yarn typedoc`
> docs: fix typedoc

- packages/entity/src/ReadonlyEntity.ts
Not sure why this wasn't an issue before but when upgraded to 0.7.0 this incorrect typing started showing up.
Fix the typing to be more specific so that methods within transaction blocks that typehint to require a transaction (only take an `EntityTransactionalQueryContext` instead of the superclass `EntityQueryContext`) don't fail to compile.
`yarn tsc`
> fix: correct type of runInTransactionAsync

- packages/entity/src/EntityCompanionProvider.ts
- packages/entity/src/EntityMutator.ts
- packages/entity/src/__tests__/EntityLoader-test.ts
- packages/entity/src/__tests__/EntityMutator-test.ts
- packages/entity/src/internal/EntityDataManager.ts
- packages/entity/src/internal/EntityTableDataCoordinator.ts
- packages/entity/src/internal/__tests__/EntityDataManager-test.ts
- packages/entity/src/metrics/EntityMetricsUtils.ts
- packages/entity/src/metrics/IEntityMetricsAdapter.ts
This adds the ability for concrete implementations of `IEntityMetricsAdapter` to segregate metric records by entity type. While not required (implementors can do whatever they like with the events), it may be helpful to find things like entity hot paths, slow tables, places that could use caches, etc.
This is not a breaking change as the interface is an object so code that worked with the old interface should work with the new interface.
Add parameter to definition and pipe through to log events.
`yarn test` (updated tests test the new behavior in addition to the old behavior to ensure no regressions).
> feat: add entityClassName to metrics adapter events

- packages/entity/src/internal/EntityDataManager.ts
- packages/entity/src/internal/__tests__/EntityDataManager-test.ts
- packages/entity/src/metrics/IEntityMetricsAdapter.ts
- packages/entity/src/metrics/NoOpEntityMetricsAdapter.ts
https://github.com/expo/entity/pull/83 added this to the other events, but they're useful in the counter metric events as well. This is technically a breaking change since it requires small changes to upgrade.
Add to interface.
`yarn tsc`
`yarn test`
> fix!: add entity name to loader counter metric events

- packages/entity-full-integration-tests/src/__integration-tests__/EntityEdgesIntegration-test.ts
- packages/entity-full-integration-tests/src/__integration-tests__/EntitySelfReferentialEdgesIntegration-test.ts
- packages/entity-full-integration-tests/src/__integration-tests__/entities/ChildEntity.ts
- packages/entity-full-integration-tests/src/__integration-tests__/entities/ParentEntity.ts
- packages/entity/src/EntityConfiguration.ts
- packages/entity/src/EntityMutator.ts
- packages/entity/src/__tests__/EntityEdges-test.ts
- packages/entity/src/__tests__/EntitySelfReferentialEdges-test.ts
The way this was created led to import cycles in top level module exports, causing them to resolve as undefined. (as described in https://medium.com/visual-development/how-to-fix-nasty-circular-dependency-issues-once-and-for-all-in-javascript-typescript-a04c987cf0de)
Make one end of the reference cycle a function to prevent necessary resolution at module import time.
1. Move integration test entities to different files in the first commit. Run `yarn integration`, ensure they fail with the following:
```
TypeError: Cannot read property 'getCompanionDefinition' of undefined
634 |       inboundEdges.map(async (entityClass) => {
635 |         return await mapMapAsync(
> 636 |           entityClass.getCompanionDefinition().entityConfiguration.schema,
|                       ^
637 | …
```
> fix: edge deletion behavior cyclic import structure

- packages/entity/src/EntityLoader.ts
- packages/entity/src/__tests__/EnforcingEntityLoader-test.ts
- packages/entity/src/__tests__/EntityLoader-test.ts
Closes https://github.com/expo/entity/issues/90.
This may be useful when a raw SQL update is run outside the entity framework, in cases like migrations or even in application code.
Add method and test.
Run test.
> feat: add ability to invalidate an entity manually

- packages/entity-full-integration-tests/src/__integration-tests__/EntitySelfReferentialEdgesIntegration-test.ts
- packages/entity-full-integration-tests/src/__integration-tests__/entities/ChildEntity.ts
- packages/entity-full-integration-tests/src/__integration-tests__/entities/ParentEntity.ts
- packages/entity/src/EntityConfiguration.ts
- packages/entity/src/EntityFields.ts
- packages/entity/src/EntityMutator.ts
- packages/entity/src/__tests__/EntityEdges-test.ts
- packages/entity/src/__tests__/EntitySelfReferentialEdges-test.ts
Apparently https://github.com/expo/entity/pull/89 wasn't sufficient for all cases. With the way entities are encouraged to be written, it seems that even with one side of this cycle being defined as a function isn't sufficient to squash all import cycles. I think this is a fairly unique case though as it is literally defining a cycle so I still don't think that having the whole companion or configuration be a function is necessary (don't foresee any other future features needing to specify other entities in configurations).
Make the other direction edge specification a function as well.
This one is harder to repro using a simple test case. To test this, I `yarn link`'ed the `entity` package into Expo code where we're seeing the behavior and ensured it fixed it.
> fix: edge deletion behavior cyclic import structure again

- packages/entity/src/utils/collections/maps.ts
A map can have undefined values on purpose, which makes it hard to distinguish from an undefined result of `Map.get` (could do a Map.has and invariant on that, but it's unnecessary in these cases since these invariants were just for programmer confidence, not API correctness or soundness).
Remove invariants.
Run tests (which test these extensively).
> fix: maps utils invariants for collections containing undefined values

- packages/entity/src/utils/testing/PrivacyPolicyRuleTestUtils.ts
b8e07f9ddc4077768980c000d61f5ddcc824e2e3 added the TID narrowing, but without the default value for `TSelectedFields` consumers would have to specify `keyof TFields` manually. All public APIs for entity should have the default, and internal APIs shouldn't need to specify it since they're fully qualified. 
Add defaults.
`yarn tsc`
> fix: add type generic default in test utils

- packages/entity/src/utils/collections/__tests__/maps-test.ts
- packages/entity/src/utils/collections/maps.ts
When a map is filtered with a predicate, if the predicate signals a type using the `is` operator, then the resulting map should be have values of the type of the predicate result. For instance, if the type `Map<string, string | null>` is filtered with a `truthy` predicate, then the return type of `filterMap` should be `Map<string, string>`.
Array accomplishes this with a function declaration overload: https://github.com/microsoft/TypeScript/blob/master/lib/lib.es5.d.ts#L1176
Add a function declaration overload.
`yarn tsc`, also run new test.
> feat: better typing on filterMap for use with predicates

- packages/entity-database-adapter-knex/src/__integration-tests__/PostgresEntityIntegration-test.ts
- packages/entity-full-integration-tests/src/__integration-tests__/EntityCacheInconsistency-test.ts
- packages/entity/src/EntityCompanionProvider.ts
- packages/entity/src/ReadonlyEntity.ts
- packages/entity/src/ViewerContext.ts
- packages/entity/src/__tests__/ReadonlyEntity-test.ts
- packages/entity/src/__tests__/ViewerContext-test.ts
This has been suggested by @jkhales and @ide a few times as a better pattern. At its core this does the same thing as the previous implementation, it just removes the unnecessary association with concrete entity types.
Move the methods to `ViewerContext`. Note that this will most likely be used in methods in `ViewerContext` subclasses in the following manner:
```typescript
// in ExpoViewerContext.ts
async runInPostgresTransactionAsync<TResult>(
transactionScope: (queryContext: EntityTransactionalQueryContext) => Promise<TResult>
): Promise<TResult> {
return await this.runInTransactionForDatabaseAdaptorFlavorAsync(
DatabaseAdapterFlavor.POSTGRES,
transactionScope
);
}
```
so that callsites don't need to specify the `DatabaseAdapterFlavor`. 
Do you think it's worth added these …
> fix: move runInTransaction to ViewerContext

- package.json
- packages/entity-full-integration-tests/src/__integration-tests__/EntityCacheInconsistency-test.ts
- packages/entity/src/EntityMutationTriggerConfiguration.ts
- packages/entity/src/EntityMutationValidator.ts
- packages/entity/src/EntityQueryContext.ts
- packages/entity/src/__tests__/EntityCompanion-test.ts
- packages/entity/src/__tests__/EntityLoader-test.ts
- packages/entity/src/__tests__/EntityMutator-test.ts
- packages/entity/src/internal/__tests__/EntityDataManager-test.ts
- packages/entity/src/rules/PrivacyPolicyRule.ts
- yarn.lock
Just general cleanup before releasing new version. No TS4.1-specific features are used.
Upgrade package, fix errors.
`yarn tsc`, run all tests.
> chore: upgrade typescript to 4.1

- packages/entity/src/EntityFields.ts
- packages/entity/src/EntityLoader.ts
- packages/entity/src/EntityMutator.ts
- packages/entity/src/__tests__/EntityFields-test.ts
Similar to how `null` is blanket allowed as a field value, `undefined` should have similar behavior for "unsetting" a mutator `setField` call.
For example, some code like:
```
mutator.setField('key', 3);
if (condition) {
// unset the field
mutator.setField('key', undefined);
}
```
Allow undefined in the base class field validation method in the same way null is allowed.
Run tests.
> fix: allow undefined value for all fields

- packages/entity/src/EntityMutationValidator.ts
This missing docblock star causes the docblock not to be included in .d.ts files or the typedoc generated documentation.
Add `*`
Wait for CI
> docs: fix docblock comment issue

- packages/entity-database-adapter-knex/src/testfixtures/PostgresTriggerTestEntity.ts
- packages/entity-database-adapter-knex/src/testfixtures/PostgresValidatorTestEntity.ts
- packages/entity/src/EntityCompanionProvider.ts
Similar to https://github.com/expo/entity/pull/89 and https://github.com/expo/entity/pull/93, we need to do the same for validators and triggers in case those import entities themselves.
I tried rethinking this whole thing and just making the companion definition a function (`static getCompanionDefinition(): () => EntityCompanionDefinition`) but it made things less clean to define (had to remove top-level consts containing companion definitions to reap benefits) and made things less composable (because consts are no longer possible, can't be shared).
Make the params functions similar to other PR examples above.
Run all tests.
> fix: mutation validator and trigger cyclic import structure

- packages/entity/src/EntityMutationTriggerConfiguration.ts
- packages/entity/src/EntityMutationValidator.ts
- packages/entity/src/EntityMutator.ts
- packages/entity/src/EntityMutatorFactory.ts
- packages/entity/src/__tests__/EntityMutator-test.ts
It's sometimes helpful to have information about what type of mutation is being executed when running validators/triggers, and in the case of update mutations what the previous value was. This is similar to the functionality expressible in rails with [ActiveModel::Dirty](https://api.rubyonrails.org/classes/ActiveModel/Dirty.html).
Some examples:
- Only allow valid field state transitions on update mutations (finite state machine)
- Run only some logic on update in a validator
Add mutation info object to trigger and validator execution functions
Run tests.
> feat: add mutation type to validator and trigger execute functions

- packages/entity-database-adapter-knex/src/testfixtures/PostgresTriggerTestEntity.ts
- packages/entity-database-adapter-knex/src/testfixtures/PostgresValidatorTestEntity.ts
- packages/entity/src/EntityMutator.ts
ef40fa5e9cdf53e25e78a9423c698e6d1c9737af didn't have a default for TSelectedFields, making implementors need to specify it unnecessarily in the default case.
Add a default.
`yarn tsc`
> fix: typescript typedef of EntityMutationInfo

- packages/entity-cache-adapter-redis/src/RedisCacheAdapter.ts
Having the cache key on field name means that field renames need to bump the cache key for the entity itself, which is non-obvious (we've been bit by it twice at Expo). Instead, it makes more sense to cache keyed by column name which is much clearer that a cache key bump is needed when changed.
Closes https://github.com/expo/entity/issues/107.
Closes ENG-291.
Change to use column name in key generation function.
Note that upgrading to a version that includes this change will cause a full entity cache invalidation of all entities. This should be fine for most applications but was why we were hesitant to make this change previously. Now the benefits outweigh the costs though.
Run all tests.
> fix: use column name instead of field name for redis cache key

- package.json
- packages/entity-cache-adapter-redis/package.json
- packages/entity-cache-adapter-redis/src/GenericRedisCacher.ts
- packages/entity-cache-adapter-redis/src/RedisCacheAdapter.ts
- packages/entity-cache-adapter-redis/src/__integration-tests__/RedisCacheAdapter-integration-test.ts
- packages/entity-cache-adapter-redis/src/index.ts
- packages/entity-cache-adapter-redis/src/testfixtures/RedisTestEntity.ts
- packages/entity-database-adapter-knex/package.json
- packages/entity-example/package.json
- packages/entity-full-integration-tests/package.json
- packages/entity-secondary-cache-redis/CHANGELOG.md
- packages/entity-secondary-cache-redis/README.md
- packages/entity-secondary-cache-redis/package.json
- packages/entity-secondary-cache-redis/src/RedisSecondaryEntityCache.ts
- packages/entity-secondary-cache-redis/src/__integration-tests__/RedisSecondaryEntityCache-integration-test.ts
- packages/entity-secondary-cache-redis/src/index.ts
- packages/entity-secondary-cache-redis/src/testfixtures/RedisTestEntity.ts
- packages/entity-secondary-cache-redis/src/testfixtures/createRedisIntegrationTestEntityCompanionProvider.ts
- packages/entity-secondary-cache-redis/tsconfig.json
- packages/entity/package.json
- packages/entity/src/EntityLoader.ts
- packages/entity/src/EntitySecondaryCacheLoader.ts
- packages/entity/src/__tests__/EnforcingEntityLoader-test.ts
- packages/entity/src/__tests__/EntityLoader-test.ts
- packages/entity/src/__tests__/EntitySecondaryCacheLoader-test.ts
- packages/entity/src/index.ts
- packages/entity/src/internal/ReadThroughEntityCache.ts
- packages/entity/src/utils/collections/__tests__/maps-test.ts
- packages/entity/src/utils/collections/maps.ts
- yarn.lock
This PR adds a concept, `EntitySecondaryCacheLoader` that allows for arbitrary entity caching and retrieval based on arbitrary load params and configurable backing store load.
The idea is that there are cases in which the standard entity caching mechanism can't be used, generally loads using `loadManyByFieldEqualityConjunctionAsync` or `loadManyByRawWhereClauseAsync` (both with limit 1), that a cache would still be useful; most commonly hot/critical paths where DB indexes aren't sufficient.
This PR adds a general purpose read-through cache for an arbitrary load of a single entity field object by any means, which then constructs and authorizes that entity as normal. Note that cache invalidation cannot be inferred for this cacher, so it must be done manually in consumer code.
For example, …
> feat: secondary cache loader

- packages/entity/src/EntityCompanionProvider.ts
- packages/entity/src/EntityConfiguration.ts
Noticed that these weren't documented on hover in vscode when using it in Expo's codebase.
Add docs.
n/a
> docs: add better docblocks for EntityCompanionDefinition and EntityConfiguration

- packages/entity-database-adapter-knex/src/PostgresEntityDatabaseAdapter.ts
- packages/entity-database-adapter-knex/src/__integration-tests__/PostgresEntityIntegration-test.ts
- packages/entity/src/EntityDatabaseAdapter.ts
- packages/entity/src/EntityLoader.ts
- packages/entity/src/utils/testing/StubDatabaseAdapter.ts
- packages/entity/src/utils/testing/__tests__/StubDatabaseAdapter-test.ts
A feature request from @jkhales for an API endpoint within the Expo server. 
Since the results for this type of load aren't stored in a dataloader or cached, we can just pipe null fieldValues directly through to the database adapters for load, and it is their duty to handle them for this type of load.
This ended up being slightly more difficult than anticipated but not too bad. Complications:
- `ANY(?)` cannot contain `NULL` so it needs to be split into separate `OR WHERE` but within the same conjunctive clause.
- Replicating the default `NULLS FIRST/LAST` postgres behavior in StubDatabaseAdapter required checking for null explicitly: https://www.postgresql.org/docs/8.3/queries-order.html#:~:text=The-,NULLS%20FIRST,-and%20NULLS%20LAST
Run tests.
> feat: allow null field values in loadManyByFieldEqualityConjunctionAsync

- packages/entity/src/EntityMutationTriggerConfiguration.ts
- packages/entity/src/EntityMutationValidator.ts
- packages/entity/src/EntityMutator.ts
There is a use case for triggers to run in two phases:
1. Phase 1 runs during the transaction, and collects data for use in phase 2
2. Phase 2 runs after the transaction and operates on data collected in phase 1, but in a non-transactional context
The way to implement this is with a transactional trigger that calls `queryContext.appendPostTransactionCallback` for phase 2. That method is only available on `EntityTransactionalQueryContext`, and since we can be guaranteed that these types of triggers have a transactional query context we can type it as such.
Update the types to match reality.
`yarn tsc`
> feat: use better QueryContext types for transactional triggers and validators

- packages/entity/src/EntityMutator.ts
- packages/entity/src/EntityQueryContext.ts
- packages/entity/src/__tests__/EntityMutator-MutationCacheConsistency-test.ts
The issue we're seeing is:
- A post-commit trigger is calling load on data that was deleted. This call should be possible (using loadNullable).
- The cache still has data in it since the ordering of post-commit callbacks is undefined.
- The data is loaded even though it no longer exists.
To fix this, add some strict ordering to post-commit callbacks to ensure that post-commit invalidations run before any other callbacks. This ensures that the post-commit callbacks that access the cache have consistent cache loads.
- Run the new test without the fix, see that it fails (the exception is thrown)
- Run the new test with the fix, see that it passes.
> fix: separate post-commit invalidation callbacks from trigger and user callbacks

- packages/entity-database-adapter-knex/src/testfixtures/PostgresTriggerTestEntity.ts
- packages/entity-database-adapter-knex/src/testfixtures/PostgresValidatorTestEntity.ts
- packages/entity/src/EntityMutationInfo.ts
- packages/entity/src/EntityMutationTriggerConfiguration.ts
- packages/entity/src/EntityMutationValidator.ts
- packages/entity/src/EntityMutator.ts
- packages/entity/src/__tests__/EntityEdges-test.ts
- packages/entity/src/__tests__/EntityMutator-MutationCacheConsistency-test.ts
- packages/entity/src/__tests__/EntityMutator-test.ts
- packages/entity/src/index.ts
The use case for this is as follows:
- We have a trigger that we want to execute to prevent deletion of an entity in certain cases but not others.
- In a normal deletion case, we want to prevent deletion if it is the last remaining entity of its type.
- In a cascade deletion case, we want to allow deletion even if it is the last remaining entity of its type so that it doesn't become orphaned.
This feature lets us solve this by inspecting the value of the cascade to see what case it's being deleted in. If it is being deleted in the normal case (no cascading info or different type of cascade) then we block the deletion in a beforeDelete trigger. If it is being deleted in a cascade deletion case we allow the deletion.
Run tests.
> feat: add cascading deletion info

- packages/entity-database-adapter-knex/src/__integration-tests__/PostgresEntityIntegration-test.ts
- packages/entity/src/EntityQueryContext.ts
- packages/entity/src/EntityQueryContextProvider.ts
- packages/entity/src/__tests__/EntityQueryContext-test.ts
There are a lot of pieces of logic in our code that are similar in nature and contain all the following qualities:
- Execute during a postgres transaction (transactional query context)
- Non-transactional call to third-party service/dependency that throws when call is invalid or service is down. Think a call to stripe, bigquery log, etc.
- Critical for consistency. If the third party call throws, the transaction should roll back.
- Should be run as late as possible in the transaction. Or, put another way, if the transaction fails (code in transaction block throws) prior to this, this code should not be run.
- There are places where we have multiple of these types of calls and they need to be ordered according to some heuristic that the application determines.
Triggers unfortunately don't …
> feat: add pre-commit callbacks on EntityQueryContext

- packages/entity-database-adapter-knex/package.json
- yarn.lock
Upgrades knex to 1.x internally. This changes the behavior of `returning` but not in a way that affects how the knex adapter uses it: `returning('*')` behaves the same as before.
This does, however, change the TypeScript declarations for knex, which changed from:
```
Knex<TRecord extends {} = any, TResult = unknown[]>
```
to:
```
Knex<TRecord extends {} = any, TResult = Record<string, any>[]>
```
`yarn test`
> feat: Upgrade knex to 1.x in `@expo/entity-database-adapter-knex`

- packages/entity-cache-adapter-redis/src/GenericRedisCacher.ts
- packages/entity-cache-adapter-redis/src/RedisCacheAdapter.ts
- packages/entity-cache-adapter-redis/src/__integration-tests__/GenericRedisCacher-integration-test.ts
- packages/entity-secondary-cache-redis/src/RedisSecondaryEntityCache.ts
- packages/entity/src/EntityCacheAdapter.ts
- packages/entity/src/internal/ReadThroughEntityCache.ts
- packages/entity/src/internal/__tests__/ReadThroughEntityCache-test.ts
- packages/entity/src/utils/testing/StubCacheAdapter.ts
Move the cache object <=> entity object transformation to be the Generic Redis Cache Adapter's responsibility.  Followup from https://github.com/expo/entity/pull/152#pullrequestreview-873411001
> move responsibility of transformer to generic redis cacher

- CHANGELOG.md
- packages/entity-cache-adapter-redis/CHANGELOG.md
- packages/entity-cache-adapter-redis/src/GenericRedisCacher.ts
- packages/entity-secondary-cache-redis/src/RedisSecondaryEntityCache.ts
- packages/entity/CHANGELOG.md
- packages/entity/src/GenericSecondaryEntityCache.ts
- packages/entity/src/IEntityGenericCacher.ts
- packages/entity/src/index.ts
Interfaces and abstract classes for generic cachers and secondary entity caches. Followup from https://github.com/expo/universe/pull/9106#pullrequestreview-879787342
The plan is to have:
- [GenericRedisCacher ](https://github.com/expo/entity/blob/master/packages/entity-cache-adapter-redis/src/GenericRedisCacher.ts)(from the entity package) and GenericLocalMemoryCacher implement GenericCacher?
- [SecondaryRedisEntityCache](https://github.com/expo/entity/blob/master/packages/entity-secondary-cache-redis/src/RedisSecondaryEntityCache.ts) (from the entity package) and LocalMemoryAndRedisSecondaryEntityCache extending GenericSecondaryEntityCache?
> chore: refactor cachers to use an abstract class and interface

- package.json
- packages/entity-cache-adapter-local-memory/CHANGELOG.md
- packages/entity-cache-adapter-local-memory/README.md
- packages/entity-cache-adapter-local-memory/package.json
- packages/entity-cache-adapter-local-memory/src/GenericLocalMemoryCacher.ts
- packages/entity-cache-adapter-local-memory/src/LocalMemoryCacheAdapter.ts
- packages/entity-cache-adapter-local-memory/src/LocalMemoryCacheAdapterProvider.ts
- packages/entity-cache-adapter-local-memory/src/__integration-tests__/LocalMemoryCacheAdapter-integration-test.ts
- packages/entity-cache-adapter-local-memory/src/__tests__/LocalMemoryCacheAdapter-test.ts
- packages/entity-cache-adapter-local-memory/src/testfixtures/LocalMemoryTestEntity.ts
- packages/entity-cache-adapter-local-memory/src/testfixtures/createLocalMemoryIntegrationTestEntityCompanionProvider.ts
- packages/entity-cache-adapter-local-memory/tsconfig.json
- yarn.lock
Moved the local memory cacher into the entity repo from www with a couple differences:
- upgrade to the newest `lru-cache` major version. The types are behind -- i can submit an upstream change to definitely typed, but in the meantime, i've made a new 'options' type for the lru cache constructor.
- added extra tests to increase test coverage
> feat: add local memory cache package 

- package.json
- packages/entity-cache-adapter-local-memory/README.md
- packages/entity-cache-adapter-local-memory/src/LocalMemoryCacheAdapterProvider.ts
- packages/entity-cache-adapter-local-memory/src/__tests__/LocalMemoryCacheAdapter-full-test.ts
- packages/entity-cache-adapter-local-memory/src/index.ts
- packages/entity-cache-adapter-local-memory/src/testfixtures/createLocalMemoryTestEntityCompanionProvider.ts
- packages/entity-secondary-cache-local-memory/CHANGELOG.md
- packages/entity-secondary-cache-local-memory/README.md
- packages/entity-secondary-cache-local-memory/package.json
- packages/entity-secondary-cache-local-memory/src/LocalMemorySecondaryEntityCache.ts
- packages/entity-secondary-cache-local-memory/src/__tests__/LocalMemorySecondaryEntityCache-test.ts
- packages/entity-secondary-cache-local-memory/src/index.ts
- packages/entity-secondary-cache-local-memory/tsconfig.json
- packages/entity-secondary-cache-redis/src/RedisSecondaryEntityCache.ts
- packages/entity/src/ComposedEntityCacheAdapter.ts
- packages/entity/src/ComposedSecondaryEntityCache.ts
- packages/entity/src/__tests__/ComposedCacheAdapter-test.ts
- packages/entity/src/__tests__/ComposedSecondaryEntityCache-test.ts
- yarn.lock
This PR imports some features from Expo's internal testing ground:
- ComposedCacheAdapter - a cache adapter that composes other cache adapters
- ComposedSecondaryCache - a secondary cache that composes other secondary caches
- LocalMemorySecondaryCache - a LRUCache secondary cache (uses local memory stuff from https://github.com/expo/entity/pull/158)
Add features and tests.
Wait for CI.
> feat: composed cache adapter, composed secondary cache, local memory secondary cache

- packages/entity-example/src/entities/AllowIfUserOwnerPrivacyRule.ts
- packages/entity/src/Entity.ts
- packages/entity/src/EntityAssociationLoader.ts
- packages/entity/src/EntityLoader.ts
- packages/entity/src/EntityLoaderFactory.ts
- packages/entity/src/EntityMutationInfo.ts
- packages/entity/src/EntityMutator.ts
- packages/entity/src/EntityMutatorFactory.ts
- packages/entity/src/EntityPrivacyPolicy.ts
- packages/entity/src/ReadonlyEntity.ts
- packages/entity/src/ViewerScopedEntityLoaderFactory.ts
- packages/entity/src/ViewerScopedEntityMutatorFactory.ts
- packages/entity/src/__tests__/EntityCommonUseCases-test.ts
- packages/entity/src/__tests__/EntityEdges-test.ts
- packages/entity/src/__tests__/EntityLoader-constructor-test.ts
- packages/entity/src/__tests__/EntityLoader-test.ts
- packages/entity/src/__tests__/EntityMutator-test.ts
- packages/entity/src/__tests__/EntityPrivacyPolicy-test.ts
- packages/entity/src/__tests__/EntitySecondaryCacheLoader-test.ts
- packages/entity/src/__tests__/ViewerScopedEntityLoaderFactory-test.ts
- packages/entity/src/__tests__/ViewerScopedEntityMutatorFactory-test.ts
- packages/entity/src/rules/AlwaysAllowPrivacyPolicyRule.ts
- packages/entity/src/rules/AlwaysDenyPrivacyPolicyRule.ts
- packages/entity/src/rules/AlwaysSkipPrivacyPolicyRule.ts
- packages/entity/src/rules/PrivacyPolicyRule.ts
- packages/entity/src/rules/__tests__/AlwaysAllowPrivacyPolicyRule-test.ts
- packages/entity/src/rules/__tests__/AlwaysDenyPrivacyPolicyRule-test.ts
- packages/entity/src/rules/__tests__/AlwaysSkipPrivacyPolicyRule-test.ts
- packages/entity/src/utils/testing/PrivacyPolicyRuleTestUtils.ts
Just like cascading info was added into triggers in https://github.com/expo/entity/pull/145, this information may be useful when evaluating a privacy policy.
Concretely we have the following use case:
- User has permission to create an object owned by a parent object (user has permission on parent object, privacy policy of child object is derived from permission on parent object). On this object the user's ID is recorded for audit purposes with SET_NULL behavior on the column.
- User creates that object
- User's permission is revoked on parent object but child object is still there (since revoking permission doesn't mean that the data should no longer exist) and therefore still references user.
- User deletes their account, and therefore the SET_NULL deletion behavior is executed. …
> feat: privacy policy evaluation context

- package.json
- packages/entity-cache-adapter-local-memory/src/GenericLocalMemoryCacher.ts
- packages/entity-cache-adapter-local-memory/src/__tests__/GenericLocalMemoryCacher-test.ts
- packages/entity-cache-adapter-local-memory/src/__tests__/LocalMemoryCacheAdapter-test.ts
- yarn.lock
`lru-cache` was resolving to 6.0.0 in the workspace root, which is what the sub-package cache-adapter-local-memory was using even though it required 7.x. I'm not sure why workspaces behaves this way, but the only way I could figure out how to fix it was to require 7.x in the root package.json.
I also looked into `nohoist` but it didn't seem to work as I would have expected: https://classic.yarnpkg.com/blog/2018/02/15/nohoist/.
Update base package.json.
Run all tests with new version, see it was failing until new argument formats were included.
> fix: lru-cache yarn workspace version resolution

- packages/entity/src/EntityMutator.ts
- packages/entity/src/EntityQueryContext.ts
Noticed these missing docblocks when using these query contexts.
Closes ENG-4925.
Add docblock.
N/A
> docs: update docblock for EntityQueryContext classes

- packages/entity/src/EntityPrivacyPolicy.ts
- packages/entity/src/internal/EntityDataManager.ts
- packages/entity/src/internal/__tests__/EntityDataManager-test.ts
- packages/entity/src/metrics/IEntityMetricsAdapter.ts
- packages/entity/src/metrics/NoOpEntityMetricsAdapter.ts
We don't need three methods for dataloader load count metrics. Instead, just use a type. This way consumers don't need to repeat code.
Also add docblocks in various places.
Closes ENG-5233.
Add type, use `tsc` to ensure it works.
`yarn tsc`
> chore: clean up metrics API a bit and add docblocks

- packages/entity-cache-adapter-local-memory/src/LocalMemoryCacheAdapter.ts
- packages/entity-cache-adapter-redis/src/RedisCacheAdapter.ts
- packages/entity-example/src/routers/notesRouter.ts
- packages/entity/src/EntityLoader.ts
- packages/entity/src/__tests__/ComposedCacheAdapter-test.ts
- packages/entity/src/errors/EntityInvalidFieldValueError.ts
- packages/entity/src/errors/EntityNotFoundError.ts
- packages/entity/src/internal/EntityDataManager.ts
- packages/entity/src/internal/EntityFieldTransformationUtils.ts
- packages/entity/src/internal/ReadThroughEntityCache.ts
- packages/entity/src/utils/testing/StubDatabaseAdapter.ts
- yarn.lock
Why
---
There were some automated security notices about outdated npm package versions, many of which often can be addressed with minor dependency upgrades.
How
---
Deleted and regenerated yarn.lock, which affects this repo but not consumers of these packages. However, TypeScript 4.7 has a change where it considers stringifying a Symbol to be a potential error. This commit explicitly stringifies keys (entity field names).
I opted for `String(fieldName)` over constraining the field name with `N extends string & keyof TFields` because adding `string &` is "viral" in the sense that lots of files including users of Entity would need to add `string &`. Also, using Symbol field names probably would work fine, they just need to be stringified before printing them.
There were also some Koa router …
> [npm][ts] Upgrade all minor npm deps incl. TS 4.7

- .github/workflows/tests.yml
Node 16 is LTS now and 12 is unsupported. 18 is also now released and we will one day run on it so this makes sure one of our major dependencies works on Node 18.
Changed the Node version in the GHA workflow file.
All tests pass, no changes needed.
> [tests] Run tests on Node 18 instead of Node 12

- .github/workflows/tests.yml
The main branch was changed from `master` to `main`, but the CI wasn't updated. This is causing codecov and CI not to run on the main branch.
Update the workflow.
Wait for CI.
> fix: fix workflow branch specification

- packages/entity-full-integration-tests/src/__integration-tests__/EntityCacheInconsistency-test.ts
- packages/entity-full-integration-tests/src/__integration-tests__/EntitySelfReferentialEdgesIntegration-test.ts
- packages/entity-full-integration-tests/src/__integration-tests__/entities/ChildEntity.ts
- packages/entity/src/Entity.ts
- packages/entity/src/EntityFieldDefinition.ts
- packages/entity/src/EntityMutationInfo.ts
- packages/entity/src/EntityMutator.ts
- packages/entity/src/EntityMutatorFactory.ts
- packages/entity/src/ViewerScopedEntityMutatorFactory.ts
- packages/entity/src/__tests__/EntityEdges-test.ts
- packages/entity/src/__tests__/EntityMutator-test.ts
- packages/entity/src/__tests__/EntitySelfReferentialEdges-test.ts
- packages/entity/src/__tests__/ViewerScopedEntityMutatorFactory-test.ts
Previously it was recommended to use `EntityEdgeDeletionBehavior.CASCADE_DELETE_INVALIDATE_CACHE` when the database was set up to do `ON DELETE SET NULL`, but this had the bug where the deletion triggers would be run for the entity that was not actually being deleted by the DBMS (it was just being updated).
The correct solution before this PR was to use `EntityEdgeDeletionBehavior.SET_NULL` and rely upon entity to do the right thing.
This PR introduces a new `EntityEdgeDeletionBehavior` for the `ON DELETE SET NULL` case, `EntityEdgeDeletionBehavior.SET_NULL_INVALIDATE_CACHE_ONLY`, which runs the update triggers (and update cache invalidations) but rely upon the dbms for the actual underlying data update.
Add new mode and tests.
Notes:
- This corrects the odd cascading info passing to the …
> feat: add EntityEdgeDeletionBehavior.SET_NULL_INVALIDATE_CACHE_ONLY

- packages/entity/src/ComposedEntityCacheAdapter.ts
- packages/entity/src/__tests__/ComposedCacheAdapter-test.ts
This PR recaches the values of lower cache layers missing from the higher layers of a ComposedCacheAdapter.
Consider a ComposedCacheAdapter with a local memory cache and a redis cache. In www, values typically stay in Redis much longer than they stay in Local Memory (capped to 5 seconds). In the scenario that a value is already cached in Redis but no longer cached in Local Memory (either it expired or was not the machine that originally cached to Redis), we will consider this a cache hit. Because the only time we cache values is when we fetch from DB, we will continually fetch from Redis until the value is evicted, at which point we will cache back into all the layers.
A better system would be to recache the higher layers with values found in the lower layers so we aren't loading from …
> [fix/feat] recache values in higher layers for composed cache adapter

- .github/workflows/docs.yml
https://github.com/expo/entity/runs/7752849180?check_suite_focus=true
Upgrade to same as `test` action.
Wait for CI
> ci: fix node version in docs action

- README.md
Found a better way to release. The only downside is that it doesn't run tests but I think that's ok.
Update readme.
Just followed these steps for the 0.27.0 release.
> chore: update readme for easier release

- packages/entity-database-adapter-knex/src/EntityFields.ts
- packages/entity-database-adapter-knex/src/PostgresEntityDatabaseAdapter.ts
- packages/entity-database-adapter-knex/src/__integration-tests__/PostgresEntityIntegration-test.ts
- packages/entity-database-adapter-knex/src/__tests__/EntityFields-test.ts
- packages/entity-database-adapter-knex/src/index.ts
- packages/entity-database-adapter-knex/src/testfixtures/PostgresTestEntity.ts
- packages/entity/src/EntityFields.ts
- packages/entity/src/__tests__/EntityFields-test.ts
Noticed by @FiberJW in https://github.com/expo/universe/pull/10420#discussion_r953010810. Knex (node-postgres) represents the BIGINT type as a string, so using `IntField` is incorrect. 
This fixes that by adding a `BigInt` field that is of string type.
Run new test case.
> feat: add BigIntField

- packages/entity-database-adapter-knex/src/PostgresEntityQueryContextProvider.ts
- packages/entity-database-adapter-knex/src/__integration-tests__/PosgresEntityQueryContextProvider-test.ts
- packages/entity-database-adapter-knex/src/__integration-tests__/PostgresEntityIntegration-test.ts
- packages/entity-database-adapter-knex/src/__integration-tests__/PostgresEntityQueryContextProvider-test.ts
- packages/entity-database-adapter-knex/src/testfixtures/PostgresUniqueTestEntity.ts
- packages/entity-example/src/adapters/InMemoryQueryContextProvider.ts
- packages/entity/src/EntityQueryContext.ts
- packages/entity/src/EntityQueryContextProvider.ts
- packages/entity/src/__tests__/EntityQueryContext-test.ts
- packages/entity/src/utils/testing/StubQueryContextProvider.ts
There's a bug in the Expo server of the following nature:
```typescript
await viewerContext.runInTransactionForDatabaseAdaptorFlavorAsync(
'postgres',
async (queryContext) => {
const testEntity = await TestEntity.loader(viewerContext, queryContext)
.enforcing()
.loadByIDAsync(id);
const testEntity2 = await TestEntity.loader(viewerContext, queryContext)
.enforcing()
.loadByIDAsync(id2);
try {
await TestEntity.updater(testEntity, queryContext)
.setField('unique_field', 'non-unique-value')
.enforceUpdateAsync();
} catch {}
// this never runs since the transaction was aborted, even though the catch caught the exception
await TestEntity.updater(testEntity2).setField('blah', 'wat').enforceUpdateAsync();
}
);
```
The exact text of the error is `current transaction is aborted` (for postgres …
> feat: nested transactions

- packages/entity/src/EntityMutationTriggerConfiguration.ts
The docblock for the afterAll trigger used to say that the triggers were run before create/update/delete operations. s/before/after/
> docs: fix typo describing afterAll trigger

- packages/entity-cache-adapter-redis/src/GenericRedisCacher.ts
- packages/entity-cache-adapter-redis/src/RedisCacheAdapter.ts
- packages/entity-cache-adapter-redis/src/__integration-tests__/GenericRedisCacher-integration-test.ts
- packages/entity-cache-adapter-redis/src/__integration-tests__/RedisCacheAdapter-integration-test.ts
- packages/entity-cache-adapter-redis/src/__integration-tests__/errors-test.ts
- packages/entity-full-integration-tests/src/__integration-tests__/EntityCacheInconsistency-test.ts
- packages/entity-full-integration-tests/src/__integration-tests__/EntityEdgesIntegration-test.ts
- packages/entity-full-integration-tests/src/__integration-tests__/EntitySelfReferentialEdgesIntegration-test.ts
- packages/entity-secondary-cache-redis/src/__integration-tests__/RedisSecondaryEntityCache-integration-test.ts
Required part of base commit of https://github.com/expo/entity/pull/199 (https://github.com/expo/entity/pull/198) for https://github.com/expo/entity/pull/199 to function.
This is just an interface which allows us to do things like batching and sharding within the interface. This allows for quicker experimentation as larger entity changes are not necessary.
Change to interface. Use the interface.
Run all tests.
> feat: change redis cache adapter to use redis-like interface

- package.json
- packages/entity-cache-adapter-redis/src/__integration-tests__/BatchedRedisCacheAdapter-integration-test.ts
- packages/entity-cache-adapter-redis/src/testfixtures/createRedisIntegrationTestEntityCompanionProvider.ts
- yarn.lock
Add example of how to coalesce mgets within the redis interface. This will allow multiple entity companion instances (multiple requests) to more efficiently fetch values from redis.
Use `@expo/batcher` to batch `mgets`. The other `IRedis` methods are not batched and probably don't need to be since they aren't used as frequently.
Run new test.
> feat: add example of redis mget batching using @expo/batcher

- packages/entity-database-adapter-knex/package.json
- yarn.lock
Trying to upgrade this where we use it, but it is resulting in conflicting typescript types I believe. https://github.com/expo/universe/pull/11100
https://nvd.nist.gov/vuln/detail/CVE-2016-20018 says Knex has a SQL injection that can cause the WHERE clause to be ignored. It's unclear how this is triggered, and due to the usage pattern within entity it is doubtful that it affects us, but still good to stay upgraded.
How
---
Upgrade to Knex 2.3.0. This is a major semver upgrade. However, the breaking change in 2.3.0 was adding back support for sqlite3. That does not affect us. I read through the changelog and saw no other changes that would affect us, though there is better support for JSONB and Postgres now: https://github.com/knex/knex/pull/5201
Run all tests.
> [www] Upgrade knex to 2.3.0

- packages/entity-database-adapter-knex/package.json
- yarn.lock
https://github.com/expo/entity/security/dependabot/59
Upgrade to 2.4.1 (2.4.0 had an regression that affected us and was caught by our integration tests: https://github.com/knex/knex/issues/5430).
Run all tests.
> chore: upgrade knex to 2.4.1 for CVE-2016-20018

- package.json
- packages/entity-cache-adapter-redis/package.json
- packages/entity-secondary-cache-redis/package.json
- yarn.lock
Similar upgrade in the Expo server: https://github.com/expo/universe/pull/11246
Changelog: https://github.com/luin/ioredis/blob/main/CHANGELOG.md
Upgrade
Run all unit and integration tests in redis cache adapter pakage(s).
> chore: upgrade ioredis to 5.2.5

- packages/entity/src/EnforcingEntityLoader.ts
- packages/entity/src/EntityLoader.ts
- packages/entity/src/__tests__/EnforcingEntityLoader-test.ts
- packages/entity/src/__tests__/EntityLoader-test.ts
Several places (about five) in our codebase call `loadFirstByFieldEqualityConjunction` with `{ limit: 1 }` either to get just the first row or to test for the existence of any matching row. The intent of the callers is often to get the latest row (limit 1, order by a descending timestamp). This PR adds a convenience method for that use case, primarily to help the callers convey their intent better, rather than saving one line of code by removing the need to specify `limit: 1`.
Added `loadFirstByFieldEqualityConjunction` to EntityLoader and EnforcingEntityLoader. This new method calls into `loadManyByFieldEqualityConjunction` and passes in `limit: 1`. It uses TS to prevent `limit` from being specified from the outside, which indicates a programming error. It also requires `orderBy` to be …
> [rfc] loadFirstByFieldEqualityConjunction, a convenience method

- packages/entity-database-adapter-knex/src/PostgresEntityQueryContextProvider.ts
- packages/entity-database-adapter-knex/src/__integration-tests__/PostgresEntityIntegration-test.ts
- packages/entity-example/src/adapters/InMemoryQueryContextProvider.ts
- packages/entity/src/EntityQueryContext.ts
- packages/entity/src/EntityQueryContextProvider.ts
- packages/entity/src/ViewerContext.ts
- packages/entity/src/__tests__/EntityQueryContext-test.ts
- packages/entity/src/internal/__tests__/EntityDataManager-test.ts
- packages/entity/src/utils/testing/StubQueryContextProvider.ts
Expo has a need for serializable transaction isolation level. This change allows specifying this configuration for knex.
Add transaction config, pass through (with translation particular to the adaptor flavor).
Run new tests.
> feat: add ability to specify knex transaction config

- packages/entity-cache-adapter-redis/README.md
- packages/entity-cache-adapter-redis/src/GenericRedisCacher.ts
- packages/entity-cache-adapter-redis/src/__integration-tests__/BatchedRedisCacheAdapter-integration-test.ts
- packages/entity-cache-adapter-redis/src/__integration-tests__/GenericRedisCacher-full-integration-test.ts
- packages/entity-cache-adapter-redis/src/__integration-tests__/GenericRedisCacher-integration-test.ts
- packages/entity-cache-adapter-redis/src/__integration-tests__/errors-test.ts
- packages/entity-cache-adapter-redis/src/__tests__/GenericRedisCacher-test.ts
- packages/entity-full-integration-tests/src/__integration-tests__/EntityCacheInconsistency-test.ts
- packages/entity-full-integration-tests/src/__integration-tests__/EntityEdgesIntegration-test.ts
- packages/entity-full-integration-tests/src/__integration-tests__/EntitySelfReferentialEdgesIntegration-test.ts
- packages/entity-secondary-cache-redis/src/__integration-tests__/RedisSecondaryEntityCache-integration-test.ts
This was added in the initial commit https://github.com/expo/entity/commit/ebe5ffdaea5583b3fa699ef77fff15fec4b114eb#diff-7060247da0b983e4354f340658d6c10fc547b357df02344a42921f6204399c22R19 but was never used. Only the cacheKeyVersion from each entity configuration is used.
In www we just put it in the prefix, which is sufficient and serves the same purpose: 
```
const REDIS_CACHER_KEY_VERSION = 1;
const REDIS_CACHER_KEY_PREFIX = `v${REDIS_CACHER_KEY_VERSION}`;
```
Remove, `tsc`
CI
> fix: remove unused field from redis configuration

- packages/entity/src/EnforcingEntityLoader.ts
- packages/entity/src/EntityLoader.ts
- packages/entity/src/__tests__/EnforcingEntityLoader-test.ts
- packages/entity/src/__tests__/EntityLoader-test.ts
Found a use case for this method in our use of the entity library. Easy enough to implement.
Add method, add tests.
Run tests.
> feat: add loadManyByIDsNullableAsync loader method

- packages/entity/src/EntityMutationTriggerConfiguration.ts
Closes ENG-10520.
These docblocks were unclear and/or incorrect.
Fix.
Proofread.
> docs: fix EntityMutationTrigger docblocks

- packages/entity-cache-adapter-local-memory/src/LocalMemoryCacheAdapterProvider.ts
- packages/entity-cache-adapter-local-memory/src/__tests__/GenericLocalMemoryCacher-full-test.ts
- packages/entity-cache-adapter-local-memory/src/testfixtures/createLocalMemoryTestEntityCompanionProvider.ts
- packages/entity-secondary-cache-local-memory/src/__tests__/LocalMemorySecondaryEntityCache-test.ts
- packages/entity/src/IEntityCacheAdapterProvider.ts
Closes ENG-6773.
The responsibility of defining the scope of how broadly or narrowly the shared cache should be shared should be the responsibility of the application. This way, the application can decide to share it amongst all requests or just have it be per-request (unlikely, but shouldn't be dictated by library).
Ref: https://github.com/expo/universe/pull/10701#pullrequestreview-1143120207
Make `localMemoryCacheAdapterMap` per-instance of the `LocalMemoryCacheAdapterProvider`. Applications should create one instance of this provider per shared scope.
Run tests.
> BREAKING CHANGE: hoist the responsibility of sharing local memory cache adapter into application

- packages/entity/src/EntityFields.ts
- packages/entity/src/__tests__/EntityFields-test.ts
Why
---
Currently the UUIDField type supports only UUIDv1-5 and to use a newer UUID version we need to use StringField.
How
---
Manually implemented UUID validation, adding support for versions 6, 7, and 8. Also added support for the "max" UUID, which is now part of the spec.
Test Plan
---
Added a UUIDv7 value (from https://uuid7.com/) to the test cases.
> feat: Allow UUIDv6/7/8 in UUIDField validation

- packages/entity/src/EntityFields.ts
- packages/entity/src/__tests__/EntityFields-test.ts
- packages/entity/src/__tests__/cases/TwoEntitySameTableDisjointRows-test.ts
Not having this more strict validation I think was an oversight. But it's too late to add it to EnumField since there needs to be a path to gradually migrate since some fields may not be providing valid values currently.
Add StrictEnumField, which also takes the enum type as an argument and validates against the possible values.
Run test.
> feat: Add StrictEnumField with better validation

- codecov.yml
This package is purely for demonstration purposes, and while it does have tests, they're more to demonstrate a testing strategy for an application that uses entity rather than as a thing that needs test coverage in this repo.
Ignore the package.
Wait for CI.
> chore: ignore entity-example package from codecov

- codecov.yml
For some reason, codecov still defaults to master for the default branch.
Explicitly specify default branch.
```
$ curl -X POST --data-binary @codecov.yml https://codecov.io/validate
Valid!
{
"codecov": {
"branch": "main"
},
"ignore": [
"^packages/entity-example.*"
]
}
```
> chore: set codecov default branch

- packages/entity/src/EntityPrivacyPolicy.ts
- packages/entity/src/EntityQueryContext.ts
- packages/entity/src/__tests__/EntityPrivacyPolicy-test.ts
- packages/entity/src/__tests__/EntityQueryContext-test.ts
Noticed that the test coverage of this was missing. Similar to https://github.com/expo/entity/pull/227, this was easy enough to add some coverage for (and it's important to have tests for this).
Add tests.
Run tests.
> chore: add more tests for privacy policy rules and nested transaction query contexts

- packages/entity/src/EntityLoader.ts
- packages/entity/src/__tests__/EnforcingEntityLoader-test.ts
- packages/entity/src/__tests__/EntityLoader-test.ts
Similar to https://github.com/expo/entity/pull/228, there was some missing coverage for the loader. This completes the coverage.
Add tests.
Run tests, verify coverage.
> chore: add more tests for entity loader

- packages/entity/src/utils/testing/__tests__/PrivacyPolicyRuleTestUtils-test.ts
- packages/entity/src/utils/testing/__tests__/StubDatabaseAdapter-test.ts
Similar to https://github.com/expo/entity/pull/229, this adds more tests for pieces of the code that are untested.
Add test, check coverage.
Run test, check coverage.
> chore: add more tests for stub database adapter and test utils

- packages/entity/src/internal/EntityFieldTransformationUtils.ts
- packages/entity/src/internal/__tests__/EntityFieldTransformationUtils-test.ts
- packages/entity/src/internal/__tests__/ReadThroughEntityCache-test.ts
This PR brings the test coverage of entity to 100%.
Add a few more test cases for things missing test cases (but still need them).
Run tests, check coverage.
> chore: add test coverage for remaining code

- packages/entity-full-integration-tests/src/__integration-tests__/EntityIntegrity-test.ts
- packages/entity/src/EntityMutator.ts
- packages/entity/src/__tests__/EntityEdges-test.ts
- packages/entity/src/__tests__/EntityMutator-test.ts
Noticed this while reading through mutator code. The issue is that previously we would not re-load the entity if `skipDatabaseUpdate` was true since we assumed the entity was unchanged. But there are some scenarios where this isn't true, namely `SET_NULL_INVALIDATE_CACHE_ONLY`.
For example, if a field in this entity is set null when cascade deleting, we want to reload it before calling the after-update triggers (especially the post-commit ones).
Closes ENG-12407.
Always re-load the entity. Note that this requires an explicit check to ensure a stable ID. Previously this check was implicitly enforced by the database adapter.
Run new tests.
> fix: always reload entity after update since cascading changes may have changed it since commit

- packages/entity-cache-adapter-local-memory/src/GenericLocalMemoryCacher.ts
- packages/entity-cache-adapter-local-memory/src/LocalMemoryCacheAdapterProvider.ts
- packages/entity-cache-adapter-redis/src/GenericRedisCacher.ts
- packages/entity-cache-adapter-redis/src/RedisCacheAdapterProvider.ts
- packages/entity-database-adapter-knex/src/PostgresEntityDatabaseAdapter.ts
- packages/entity-database-adapter-knex/src/PostgresEntityDatabaseAdapterProvider.ts
- packages/entity-example/src/adapters/InMemoryDatabaseAdapter.ts
- packages/entity-secondary-cache-local-memory/src/LocalMemorySecondaryEntityCache.ts
- packages/entity-secondary-cache-redis/src/RedisSecondaryEntityCache.ts
- packages/entity/src/EntityCompanionProvider.ts
- packages/entity/src/EntityConfiguration.ts
- packages/entity/src/EntityDatabaseAdapter.ts
- packages/entity/src/IEntityCacheAdapterProvider.ts
- packages/entity/src/IEntityDatabaseAdapterProvider.ts
- packages/entity/src/__tests__/ComposedCacheAdapter-test.ts
- packages/entity/src/__tests__/EntityMutator-test.ts
- packages/entity/src/internal/EntityDataManager.ts
- packages/entity/src/internal/EntityFieldTransformationUtils.ts
- packages/entity/src/internal/EntityTableDataCoordinator.ts
- packages/entity/src/internal/ReadThroughEntityCache.ts
- packages/entity/src/utils/testing/StubCacheAdapter.ts
- packages/entity/src/utils/testing/StubDatabaseAdapter.ts
- packages/entity/src/utils/testing/StubDatabaseAdapterProvider.ts
This allows us to remove the `any` typecast in EntityConfiguration.ts and is more correct: only string-keyed field objects are allowed.
This is in preparation for addressing this comment: https://github.com/expo/entity/pull/233#discussion_r1625121092
Add type constraint where necessary.
`yarn tsc`
> fix: constrain entity fields type to string-keyed object

- packages/entity-cache-adapter-local-memory/src/__tests__/GenericLocalMemoryCacher-full-test.ts
- packages/entity-cache-adapter-redis/src/__integration-tests__/BatchedRedisCacheAdapter-integration-test.ts
- packages/entity-cache-adapter-redis/src/__integration-tests__/GenericRedisCacher-full-integration-test.ts
- packages/entity-database-adapter-knex/src/__integration-tests__/PostgresEntityIntegration-test.ts
- packages/entity-example/src/routers/notesRouter.ts
- packages/entity/src/AuthorizationResultBasedEntityLoader.ts
- packages/entity/src/EnforcingEntityLoader.ts
- packages/entity/src/EntityAssociationLoader.ts
- packages/entity/src/EntityLoader.ts
- packages/entity/src/EntityMutator.ts
- packages/entity/src/EntitySecondaryCacheLoader.ts
- packages/entity/src/NonEnforcingEntityLoader.ts
- packages/entity/src/__tests__/EnforcingEntityLoader-test.ts
- packages/entity/src/__tests__/EntityCommonUseCases-test.ts
- packages/entity/src/__tests__/EntityLoader-constructor-test.ts
- packages/entity/src/__tests__/EntityLoader-test.ts
- packages/entity/src/__tests__/EntityMutator-test.ts
- packages/entity/src/__tests__/cases/TwoEntitySameTableDisjointRows-test.ts
- packages/entity/src/utils/EntityPrivacyUtils.ts
This has been discussed many many times and it's long overdue: it's time to make non-enforcing loads not the default. Whether we make enforcing loads the default is another discussion to be had, but is out of the scope of this PR.
This PR introduces a new required intermediate call to loaders to explicitly specify either enforcing or non-enforcing load behavior.
```diff
-    const entityResult = await TestEntity.loader(viewerContext).loadByIDAsync(id);
+    const entityResult = await TestEntity.loader(viewerContext)
+      .withAuthorizationResults()
+      .loadByIDAsync(id);
```
Note that `.enforcing` calls remain unchanged.
The reasoning behind this change is that it's too easy to misinterpret a Failure result to also be the result of the call when a database error is thrown from a …
> BREAKING CHANGE: make using non-enforcing entity loader explicit

- packages/entity-cache-adapter-local-memory/src/__tests__/GenericLocalMemoryCacher-full-test.ts
- packages/entity-cache-adapter-redis/src/__integration-tests__/BatchedRedisCacheAdapter-integration-test.ts
- packages/entity-cache-adapter-redis/src/__integration-tests__/GenericRedisCacher-full-integration-test.ts
- packages/entity/src/AuthorizationResultBasedEntityLoader.ts
- packages/entity/src/EntityLoader.ts
- packages/entity/src/EntityLoaderUtils.ts
- packages/entity/src/EntityMutator.ts
- packages/entity/src/EntitySecondaryCacheLoader.ts
- packages/entity/src/__tests__/EnforcingEntityLoader-test.ts
- packages/entity/src/__tests__/EntityLoader-test.ts
- packages/entity/src/__tests__/EntityMutator-test.ts
This is the second part of https://github.com/expo/entity/pull/238. From the summary:
> In a follow-up, I'll look into moving the common methods (the ones in knownLoaderOnlyDifferences) to a different utils class since it no longer makes sense for them not to be on the loader class. But to limit the scope of this PR, they are kept in the NonEnforcingEntityLoader class for now.
This PR is this follow-up. It creates a `utils` concept that the loaders use but also that end-users can use in rare cases (we use them in rare cases in Expo server code).
The reason for this is that it doesn't make sense to have a call of the form (what they are after #238):
`AssetEntity.loader(viewerContext, queryContext).nonEnforcing().invalidateEntityAsync(asset)`
Instead, this PR makes it: …
> chore: move entity loader utils into their own object

- packages/entity/src/EntityFieldDefinition.ts
- packages/entity/src/utils/EntityPrivacyUtils.ts
- packages/entity/src/utils/__tests__/canViewerDeleteAsync-edgeDeletionPermissionInferenceBehavior-test.ts
This PR adds a new concept for optimized evaluation of `canViewerDeleteAsync`: `EntityEdgeDeletionAuthorizationInferenceBehavior`.
The way it works is: when the method goes to recursively authorize all cascading deletes/set-nulls for an entity being checked in `canViewerDeleteAsync`, an application developer can specify that checking one instance of an edge of an association type is sufficient for inferring that all edges share the same privacy checks and loading all of them isn't necessary. Without this, all edges are loaded and authorization to cascade delete / set null are checked individually.
This is more of a best-effort optimistic evaluation to tell ahead of time whether a deletion will succeed or fail, and is not used during actual deletion since an application developer may apply …
> feat: add EntityEdgeDeletionAuthorizationInferenceBehavior for canViewerDeleteAsync

- .gitattributes
- package.json
- yarn.lock
This upgrades typescript to 5.5: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-5.html. I don't believe we use any of the new features, but still good to keep up-to-date.
Upgrade.
`yarn` (cleans and builds)
> chore: upgrade typescript and related packages

- package.json
- resources/run-with-docker
- yarn.lock
This upgrades typescript to the latest.
Look at changes on https://github.com/microsoft/TypeScript/releases between prev and this version, see nothing alarming.
Run tsc and full test suite.
> chore: upgrade typescript to 5.5.4

- packages/entity/src/__tests__/entityUtils-test.ts
- packages/entity/src/entityUtils.ts
- packages/entity/src/utils/EntityPrivacyUtils.ts
- packages/entity/src/utils/__tests__/EntityPrivacyUtils-test.ts
There's a need to debug authorization failures at the callsites of `canViewerDeleteAsync` in Expo's server code. Making this return the authorization failure should help to debug.
Add new set of functions that returns the result of the authorization check.
Add full test coverage for this new set of functions and run the tests.
> feat: add function to get authorization results for canViewerUpdateAsync/canViewerDeleteAsync

- .github/workflows/tests.yml
#255 switched barreling to `ctix` and fully-automated it (no manual intervention). But the intention is still to have the author run the command when they add new files in case they don't want the new files to be exported in the barrel.
This PR adds a CI step to ensure that the barrels are up to date.
Run `yarn ctix` and check if working directory is dirty. If so, fail the CI run.
1. Add a file with an export, `Blah.ts`, in src. Don't run `yarn ctix`.
2. Push PR
3. See CI failure.
> chore: add CI check for needing to run ctix

- README.md
- packages/entity-cache-adapter-local-memory/src/GenericLocalMemoryCacher.ts
- typedoc.json
Typedoc generation is broken on main.
Typedoc introduced a new monorepo package mode that solves the problem, so update to that.
`yarn typedoc`, view generated index.html.
> chore: fix typedoc

- packages/entity-codemod/src/transforms/__testfixtures__/v0.40.0-v0.41.0/test1.input.ts
- packages/entity-codemod/src/transforms/__testfixtures__/v0.40.0-v0.41.0/test1.output.ts
- packages/entity-codemod/src/transforms/__tests__/v0.40.0-v0.41.0-test.ts
- packages/entity-codemod/src/transforms/v0.40.0-v0.41.0.ts
Similar to #259, this creates a codemod to ease over breaking changes for large applications.
In particular, this creates the codemod for #256, which is planned to release as v1.0.0.
Create a codemod with tests.
Run automated tests.
Manual test in large application:
1. Apply changes from stack up to v0.40.0
2. Run codemod from #259, manually fix other tsc errors.
3. Apply changes from #256 (moving application libraries to v1.0.0.
4. Run this codemod, see it fixes ~99% of tsc errors.
> feat: Create codemod for v0.40.0 -> v0.41.0

- packages/entity/src/AuthorizationResultBasedEntityLoader.ts
- packages/entity/src/EnforcingEntityLoader.ts
A minor change to move docblocks of loader methods from the authorization-based loader to the enforcing loader since the enforcing methods are now the "default" (most-likely-to-be-encountered)
Move docblocks.
Proofread.
> fix: move source of truth of loader docblocks to enforcing loader since it is not the default loader

- packages/entity/src/internal/EntityDataManager.ts
- packages/entity/src/internal/__tests__/EntityDataManager-test.ts
Noticed this while building composite key loading. The issue is that this is counting the incorrect number of items being loaded from the database.
Fix field.
Add a new test for this.
> fix: fix metrics for dataloader waterfall logging

- packages/entity/src/index.ts
- packages/entity/src/utils/collections/SerializableKeyMap.ts
- packages/entity/src/utils/collections/__tests__/SerializableKeyMap-test.ts
- packages/entity/src/utils/collections/__tests__/sets-test.ts
- packages/entity/src/utils/collections/maps.ts
- packages/entity/src/utils/collections/sets.ts
This adds the utility classes needed for composite field loading as described in #201.
This adds a few concepts:
- `areSetsEqual` - simple utility for checking set equality
- `SerializableKeyMap` - a map where keys must be of a custom interface for checking equality.
Add new tests, run them. Full coverage.
> feat: add some utility classes and methods in preparation for composite keys

- package.json
- packages/entity-cache-adapter-local-memory/package.json
- packages/entity-cache-adapter-redis/package.json
- packages/entity-codemod/package.json
- packages/entity-database-adapter-knex/package.json
- packages/entity-example/package.json
- packages/entity-full-integration-tests/package.json
- packages/entity-ip-address-field/package.json
- packages/entity-secondary-cache-local-memory/package.json
- packages/entity-secondary-cache-redis/package.json
- packages/entity/package.json
- packages/entity/src/EntityConfiguration.ts
- packages/entity/src/utils/testing/StubCacheAdapter.ts
- tsconfig.json
- yarn.lock
Before doing the next release, it'll be good to update the dependencies. This PR starts this by upgrading typescript and typedoc.
Upgrade, fix typedoc warnings.
CI
> chore: upgrade typescript to 5.8 and a few other packages

- packages/entity-database-adapter-knex/src/EntityFields.ts
- packages/entity-database-adapter-knex/src/testfixtures/ErrorsTestEntity.ts
- packages/entity-database-adapter-knex/src/testfixtures/InvalidTestEntity.ts
- packages/entity-database-adapter-knex/src/testfixtures/PostgresTestEntity.ts
- packages/entity-example/src/entities/NoteEntity.ts
- packages/entity-ip-address-field/src/EntityFields.ts
- packages/entity-secondary-cache-local-memory/src/__tests__/LocalMemorySecondaryEntityCache-test.ts
- packages/entity-secondary-cache-redis/src/testfixtures/RedisTestEntity.ts
- packages/entity/src/EntityConfiguration.ts
- packages/entity/src/EntityFieldDefinition.ts
- packages/entity/src/EntityFields.ts
- packages/entity/src/__tests__/EntityCompanionProvider-test.ts
- packages/entity/src/__tests__/EntityConfiguration-test.ts
- packages/entity/src/__tests__/EntityFields-test.ts
- packages/entity/src/__tests__/EntityPrivacyPolicy-test.ts
- packages/entity/src/internal/__tests__/EntityFieldTransformationUtils-test.ts
- packages/entity/src/testfixtures/DateIDTestEntity.ts
- packages/entity/src/testfixtures/SimpleTestEntity.ts
- packages/entity/src/testfixtures/TestEntity.ts
- packages/entity/src/testfixtures/TestEntity2.ts
- packages/entity/src/testfixtures/TestEntityNumberKey.ts
- packages/entity/src/testfixtures/TestEntityWithMutationTriggers.ts
- packages/entity/src/utils/__tests__/EntityPrivacyUtils-test.ts
- packages/entity/src/utils/__tests__/canViewerDeleteAsync-edgeDeletionPermissionInferenceBehavior-test.ts
- packages/entity/src/utils/testing/describeFieldTestCase.ts
Discussed #273 offline. What we settled on was that the ID field should need to explicitly specify the cache field. This way it's still possible to not cache, especially during development of a new entity at which time having a cache can be frustrating.
The way this is accomplished is by using the newly-genericized id field to conditionally switching the type of field definition needed for the id field in the schema.
Run all tests. See that the cache field is required by tsc in the existing entities in these packages.
> feat: enforce explicit id field cache property

- packages/entity/src/EntityFieldDefinition.ts
This sentinel makes the inferred type compatibility between instances of a class with `EntityFieldDefinitionOptionsExplicitCache` incompatible with `EntityFieldDefinitionOptions`. The problem is that tsc removes types from private fields, so the generate .d.ts file didn't have an appropriate sentinel in the resulting library typedefs.
This PR fixes it by making the field protected, which seems to be the only option.
The way to test this is by trying it in a library that consumes `@expo/entity`, notably `@expo/entity-example` on the `NoteEntity` with the built .d.ts file.
> fix: fix generated tsc definition sentinel type visibility

- packages/entity/package.json
- yarn.lock
Noticed that this (major) dependency of entity has been updated. The [changelog](https://github.com/graphql/dataloader/blob/main/CHANGELOG.md) doesn't indicate anything breaking.
Upgrade.
Rely upon full test coverage for compatibility.
> chore: upgrade dataloader package

- packages/entity-database-adapter-knex/src/__integration-tests__/PostgresEntityQueryContextProvider-test.ts
- packages/entity-full-integration-tests/src/__integration-tests__/EntityCachePushSafety-test.ts
- packages/entity/package.json
- packages/entity/src/AuthorizationResultBasedEntityMutator.ts
- packages/entity/src/EntityLoaderUtils.ts
- packages/entity/src/EntityQueryContext.ts
- packages/entity/src/EntityQueryContextProvider.ts
- packages/entity/src/__tests__/AuthorizationResultBasedEntityLoader-test.ts
- packages/entity/src/__tests__/EntityQueryContext-test.ts
- packages/entity/src/internal/EntityDataManager.ts
- packages/entity/src/internal/__tests__/EntityDataManager-test.ts
- packages/entity/src/metrics/EntityMetricsUtils.ts
- packages/entity/src/metrics/IEntityMetricsAdapter.ts
This is a retry of #98. It has become more important in Expo's server application due to more things running within transactions. When it was written previously, relatively few things were transactional.
The idea is that within a transaction, subsequent reads should be able to be cached locally (dataloader) as long as the local cache is kept consistent (not in the cache adapter though).
The way this is done is to keep a dataloader map (dataloader per-entity like we do for the top-level loads) per-transaction as well. Then, when in a transaction, instead of going directly to the database, go through the transaction's dataloader before hitting the database. This way loads within the transaction are coalesced and cached locally.
Invalidation becomes more complex though. 
- We still only want …
> feat: add transaction-scoped dataloaders

- packages/entity-database-adapter-knex/src/__integration-tests__/PostgresEntityQueryContextProvider-test.ts
- packages/entity-testing-utils/src/StubDatabaseAdapter.ts
- packages/entity/src/EntityQueryContext.ts
- packages/entity/src/EntityQueryContextProvider.ts
- packages/entity/src/__tests__/EntityQueryContext-test.ts
- packages/entity/src/internal/EntityDataManager.ts
- packages/entity/src/internal/__tests__/EntityDataManager-test.ts
- packages/entity/src/utils/__testfixtures__/StubDatabaseAdapter.ts
Tested #284 in Expo's server. It turns out that there are definitely some instances where a transactional dataloader produces unexpected results. Namely of the forms:
The solution here is to use the new `TransactionalDataLoaderMode.DISABLED` for this transaction, or `TransactionalDataLoaderMode.ENABLED_BATCH_ONLY` works as well.
```typescript
async function waitUntilEntityWithIdExistsAsync(
viewerContext: ViewerContext,
queryContext: EntityTransactionalQueryContext,
id: string
): Promise<TestEntity> {
return await promiseRetry(
async (retry) => {
const retryAfterTimeoutAsync = async (error: any): Promise<never> => {
await setTimeout(1000); // 1 second between attemps
return retry(error);
};
try {
return await TestEntity.loader(viewerContext, queryContext).loadByIDAsync(id);
} catch (e) { …
```
> fix: introduce transactional dataloader mode and fix global transaction ID generation

- packages/entity-database-adapter-knex/src/__integration-tests__/EntityCreationUtils-test.ts
- packages/entity-database-adapter-knex/src/__testfixtures__/PostgresUniqueTestEntity.ts
- packages/entity/src/AuthorizationResultBasedEntityLoader.ts
- packages/entity/src/errors/EntityNotFoundError.ts
- packages/entity/src/errors/__tests__/EntityDatabaseAdapterError-test.ts
- packages/entity/src/index.ts
- packages/entity/src/utils/EntityCreationUtils.ts
- packages/entity/src/utils/__tests__/EntityCreationUtils-test.ts
This brings some utility methods from Expo's server implementation into the entity package itself and adds more tests for them within different transaction scenarios.
Closes #202.
Copy code, make more generic, add tests.
Run tests.
> feat: add createOrGetExistingAsync and createWithUniqueConstraintRecoveryAsync utility methods

- resources/jest.config.js
By default jest will only track coverage stats for files imported by a test.  What about files that are never imported by any test?  They aren't included in the report.  But it would be better to include them and mark them as having 0% coverage.
Codecov in CI will show a difference in the results.
e: It looks like it adds two untested source files to coverage, and removes two test files from it.
> chore: Explicitly list files to collect coverage from

- resources/jest.config.js
I was hoping this would be more accurate and consistent.
Codecov report from CI.
It looks like there are a few small changes here and there, and then the `src/index.ts` files were all added to coverage and marked as uncovered.
> chore: Use 'v8' coverage provider

- .npmignore
- package.json
- packages/entity-cache-adapter-local-memory/package.json
- packages/entity-cache-adapter-redis/package.json
- packages/entity-codemod/package.json
- packages/entity-database-adapter-knex/package.json
- packages/entity-ip-address-field/package.json
- packages/entity-secondary-cache-local-memory/package.json
- packages/entity-secondary-cache-redis/package.json
- packages/entity-testing-utils/package.json
- packages/entity/package.json
The most recent release included test files.
The `.npmignore` did not work!  Instead I changed each  package.json to filter the files which shouldn't be published.
- `**/__*`: we use this pattern to indicate test-only files of some kind
- `*.tsbuildinfo`: typescript uses these to track build caching 
Run `yarn package-files` from root and you'll see exactly what files will be included in each package.
> chore: Remove unneeded files from packages

- packages/entity/src/AuthorizationResultBasedEntityMutator.ts
- packages/entity/src/EntityDeleter.ts
- packages/entity/src/EntityMutatorFactory.ts
- packages/entity/src/EntityUpdater.ts
- packages/entity/src/ViewerScopedEntityMutatorFactory.ts
- packages/entity/src/__tests__/EntityMutator-test.ts
In the same way that the cascadingDeleteCause can be specified in application code during a call to the load factory method (which is the advanced way of creating a loader), it should be possible to specify for the updater and deleter when constructed via their factory methods.
Note that this doesn't affect the normal `Entity.deleter(entity).deleteAsync()` method of calling. Only when called in the following form is it specifiable from application code:
```typescript
this.existingEntity
.getViewerContext()
.getViewerScopedEntityCompanionForClass(this.entityClass)
.getMutatorFactory()
.forUpdate(this.existingEntity, this.queryContext, cascadingDeleteCause);
```
Concretely, this is useful in application code for bulk/batch deletions ahead of calling the parent entity's delete. Once #220 is …
> feat: allow manual specification of cascadingDeleteCause in delete mutator factory method

- eslint.config.js
- packages/entity-database-adapter-knex/src/__integration-tests__/PostgresEntityIntegration-test.ts
In other repositories at Expo we have this lint disallow rule to avoid accidental skips like this. This PR adds the same rule.
1. Add rule.
2. Fix violation.
`yarn lint`
> chore: fix erroneous describe.only and add lint rule to prevent it

- packages/entity/src/errors/EntityCacheAdapterError.ts
- packages/entity/src/errors/EntityError.ts
- packages/entity/src/errors/EntityInvalidFieldValueError.ts
- packages/entity/src/errors/EntityNotAuthorizedError.ts
- packages/entity/src/errors/EntityNotFoundError.ts
#311 added more documentation to database adapter errors. This PR adds it for the rest of entity errors.
Add more documentation.
Proofread.
> feat: add more documentation to entity errors

- packages/entity-example/src/adapters/InMemoryDatabaseAdapter.ts
- packages/entity-testing-utils/src/StubDatabaseAdapter.ts
- packages/entity/src/utils/__testfixtures__/StubDatabaseAdapter.ts
#311 updated the errors for postgres, but the conditions in the stub adapters preempted those errors in test code, so their behavior diverged. This PR makes the stub adapters behave more similarly to Postgres adapter.
Return more similar results in not-found cases. See inline comments.
`yarn tsc`. Also the tests in entity-example test this.
> fix: make in memory and stub database adapters behave more similarly to sql
